HOST_CC ?= cc
FISICS_CC ?= /Users/calebsv/Desktop/CodeWork/fisiCs/fisics
FISICS_FLAGS ?=
BUILD_TOOLCHAIN ?= clang
PACKAGE_TOOLCHAIN ?= $(BUILD_TOOLCHAIN)
TEST_TOOLCHAIN ?= clang
RELEASE_TOOLCHAIN ?= clang
CFLAGS ?= -std=c11 -Wall -Wextra -Werror -O2
PKG_CONFIG ?= pkg-config

PACKAGE_DISPLAY_NAME ?= eCho
PACKAGE_BUNDLE_ID ?= com.cosm.echo
PACKAGE_PROFILE ?= standard
PACKAGE_RUNTIME_NAMESPACE ?= MemConsole
PACKAGE_LOG_NAMESPACE ?= MemConsole
PACKAGE_PROGRAM_VERSION ?= $(strip $(shell cat VERSION 2>/dev/null))
PACKAGE_BUILD_LABEL ?= eCho-$(PACKAGE_PROGRAM_VERSION)
PACKAGE_EMBED_BUILD_IDENTITY ?= 0
