APP_SRCS := src/app/mem_console.c \
	src/app/mem_console_action_roles.c \
	src/app/mem_console_app_main.c \
	src/app/mem_console_app_actions.c \
	src/app/mem_console_app_db_switch.c \
	src/app/mem_console_app_events.c \
	src/app/mem_console_app_loop.c \
	src/app/mem_console_app_loop_input.c \
	src/app/mem_console_app_status.c \
	src/app/mem_console_app_theme.c \
	src/app/mem_console_workspace_authoring_host.c \
	src/app/mem_console_kernel_bridge.c \
	src/db/mem_console_db.c \
	src/db/mem_console_db_graph_load.c \
	src/db/mem_console_db_graph_sort.c \
	src/db/mem_console_db_filters.c \
	src/db/mem_console_db_mutations.c \
	src/db/mem_console_db_relationship_mutations.c \
	src/db/mem_console_db_reads.c \
	src/runtime/mem_console_prefs.c \
	src/runtime/mem_console_prefs_versions.c \
	src/runtime/mem_console_prefs_app_io.c \
	src/runtime/mem_console_runtime.c \
	src/runtime/mem_console_runtime_refresh.c \
	src/runtime/mem_console_state.c \
	src/runtime/mem_console_state_roles.c \
	src/runtime/mem_console_state_db_picker.c \
	src/runtime/mem_console_state_core.c \
	src/runtime/mem_console_state_graph_filters.c \
	src/runtime/mem_console_state_paths.c \
	src/runtime/mem_console_state_project_filters.c \
	src/layout/mem_console_layout_config.c \
	src/layout/mem_console_pane_layout.c \
	src/ui/mem_console_ui.c \
	src/ui/mem_console_ui_chrome.c \
	src/ui/mem_console_ui_common.c \
	src/ui/mem_console_ui_detail_panel.c \
	src/ui/mem_console_ui_detail_relationships.c \
	src/ui/mem_console_ui_detail_references.c \
	src/ui/mem_console_ui_detail_section.c \
	src/ui/mem_console_ui_hud.c \
	src/ui/mem_console_visual_artifact.c \
	src/ui/mem_console_workspace_authoring_overlay.c \
	src/ui/mem_console_ui_left_browse_filters.c \
	src/ui/mem_console_ui_left_panel.c \
	src/ui/mem_console_ui_left_section.c \
	src/ui/graph/mem_console_ui_graph.c \
	src/ui/graph/mem_console_ui_graph_camera.c \
	src/ui/graph/mem_console_ui_graph_controls.c \
	src/ui/graph/mem_console_ui_graph_draw.c \
	src/ui/graph/mem_console_ui_graph_geometry.c \
	src/ui/graph/mem_console_ui_graph_hud.c \
	src/ui/graph/mem_console_ui_graph_layout.c \
	src/ui/graph/mem_console_ui_graph_layout_focus_helpers.c \
	src/ui/graph/mem_console_ui_graph_layout_web.c \
	src/ui/graph/mem_console_ui_graph_mode_policy.c \
	src/ui/graph/mem_console_ui_graph_overlay.c \
	src/ui/graph/mem_console_ui_graph_project_pods.c \
	src/ui/graph/mem_console_ui_graph_status.c \
	src/ui/graph/mem_console_ui_graph_types.c \
	src/ui/graph/mem_console_ui_graph_panel.c
